---
- name: Copy jar file to inventory i.e. Pull docker image
  hosts: all
  tasks:
          - name: Pull junit devops image 
            docker_image:
                  name: mokshanandareddy/scientific_calculator 
                  source: pull
          - name : Running container
            shell: docker run -it -d mokshanandareddy/scientific_calculator
